version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
  database:
    container_name: api-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: api-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata: